name: 'CI'
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.10.0]
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.32.1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install pnpm
      run: curl -f https://get.pnpm.io/v6.14.js | node - add --global pnpm@6
    - name: install dependency
      run: pnpm install --filter=\!garfish-docs --filter=\!@garfish-dev/\*
    - name: Run unit tests
      run: pnpm test
    - name: codecov
      run: npx codecov -f coverage/*.json

  e2e-test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.10.0]
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.32.1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install pnpm
      run: curl -f https://get.pnpm.io/v6.14.js | node - add --global pnpm@6
    - name: install dependency
      run: pnpm install --filter=\!garfish-docs
    - name: build
      run:  pnpm build
    - name: Run cypress test
      uses: cypress-io/github-action@v2
      with:
        install: false
        start: node scripts/devCypress.js
        wait-on: 'http://localhost:8090,http://localhost:8091,http://localhost:8092,http://localhost:8093,http://localhost:8094,http://localhost:8095,http://localhost:8096,http://localhost:8097'
        wait-on-timeout: 120
        parallel: true
        record: true
        spec: cypress/integration/**
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        # Recommended: pass the GitHub token lets this action correctly
        # determine the unique run id necessary to re-run the checks
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
